import type { Metadata } from "next";

import "@styles/globals.css";
import { geistMono, geistSans } from "@/assets/fonts";
import { ThemeProvider } from "@providers/theme-provider";

export const metadata: Metadata = {
  title: "StreamTub",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head />
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <ThemeProvider
          attribute={"class"}
          defaultTheme={"system"}
          enableSystem
          disableTransitionOnChange
        >
          {children}
        </ThemeProvider>
      </body>
    </html>
  );
}
